In [1]:
from rl.torch_utils import *
from rl.torch_jit_utils import *
from rl.trainer import Trainer

# trainer = Trainer(57, 21)

In [2]:
import getpass

user = getpass.getuser()

In [3]:
user

'yizhou'

In [4]:
from omni.isaac.kit import SimulationApp

simulation_app = SimulationApp({"headless": True, "open_usd": f"omniverse://localhost/Users/{user}/test_humanoid_sit.usd", 
                                "livesync_usd": f"omniverse://localhost/Users/{user}/test_humanoid_sit.usd"})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-2759bf24-939d-49f0-88f5-69da2fe379f6.json

OmniAssetFileFormat


[1.548s] [ext: omni.mdl-0.1.0] startup
[1.570s] [ext: omni.kit.menu.create-1.0.2] startup
[1.571s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[1.573s] [ext: omni.kit.window.drop_support-1.0.0] startup
[1.573s] [ext: omni.kit.material.library-1.3.10] startup
[1.576s] [ext: omni.kit.window.property-1.6.3] startup
[1.578s] [ext: omni.kit.context_menu-1.3.9] startup
[1.583s] [ext: omni.kit.window.file_importer-1.0.4] startup
[1.584s] [ext: omni.kit.stage_templates-1.1.2] startup
[1.587s] [ext: omni.kit.widget.stage-2.6.15] startup
[1.592s] [ext: omni.kit.window.file-1.3.16] startup
[1.595s] [ext: omni.debugdraw-0.1.0] startup
[1.606s] [ext: omni.kit.window.content_browser-2.4.28] startup
[1.622s] [ext: omni.kit.widget.prompt-1.0.1] startup
[1.624s] [ext: omni.kit.property.usd-3.14.8] startup
[1.662s] [ext: omni.hydra.engine.stats-1.0.0] startup
[1.669s] [ext: omni.kit.widget.settings-1.0.0] startup
[1.671s] [ext: omni.graph.tools-1.3.5] startup
[1.695s] [ext: omni.graph.core-2.27.0

2022-07-21 05:56:24 [1,901ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-21 05:56:24 [1,901ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


Warp initialized:
   Version: 0.2.1
   Using CUDA device: NVIDIA GeForce RTX 3090
   Using CPU compiler: /usr/bin/g++
[6.599s] [ext: omni.kit.window.preferences-1.2.1] startup
[6.639s] [ext: omni.kit.ui_test-1.2.0] startup
[6.642s] [ext: omni.graph.ui-1.6.1] startup
[6.676s] [ext: omni.kvdb-0.0.0] startup
[6.680s] [ext: omni.kit.widget.searchfield-1.0.6] startup
[6.682s] [ext: omni.convexdecomposition-1.4.12] startup
[6.686s] [ext: omni.graph.action-1.17.0] startup
[6.702s] [ext: omni.localcache-0.0.0] startup
[6.707s] [ext: omni.usdphysics-1.4.12] startup
[6.712s] [ext: omni.graph.scriptnode-0.5.0] startup
[6.717s] [ext: omni.physx-1.4.12-5.1] startup
2022-07-21 05:56:29 [6,734ms] [Warning] [omni.kvdb.plugin] wasn't able to load the meta database, trying to repair it ...
2022-07-21 05:56:29 [6,786ms] [Warning] [omni.kvdb.plugin] repair failed
[6.794s] [ext: omni.kit.usd_undo-0.1.0] startup
[6.796s] [ext: omni.graph.nodes-1.25.0] startup
[6.814s] [ext: omni.physx.commands-1.4.12-5.1] s

In [5]:
import omni
from omni.isaac.core import World
from pxr import Gf, Sdf, UsdGeom, UsdShade

import torch
import numpy as np

In [6]:
world = World(physics_dt= 1.0 / 60, backend = "torch")

In [7]:
from omni.isaac.core.utils.stage import set_stage_up_axis

set_stage_up_axis("y")
world.get_physics_context().set_gravity(-9.81)

In [8]:
from omni.isaac.core.utils.stage import get_current_stage
UsdGeom.GetStageUpAxis(get_current_stage())

'Y'

In [9]:
world.get_physics_context()._physics_scene.GetGravityDirectionAttr().Get()

Gf.Vec3f(0.0, -1.0, 0.0)

In [10]:
# world.scene.add_default_ground_plane()

In [11]:
# get prims
len(list(world.scene.stage.TraverseAll()))

856

In [12]:
world.render()

In [13]:
from rl.robot_env import RobotEnv

env = RobotEnv("/World/envs/*/humanoid/torso")

In [14]:
world.render()

In [15]:
world.reset()

In [16]:
env.start()

simlation context torch None
num_envs 8
default joint state tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],

In [17]:
world.scene.add(env.robots)

In [18]:
total_step = 0

In [19]:
# step
def step(env, trainer, warm_up_steps = 2000):
    # action shape
    action_shape = env.action_shape
    
    # env step
    env.progress_buf += 1
    if total_step < warm_up_steps:
        actions =  torch.clamp(torch.randn(action_shape), min = -1, max = 1) / 10
    elif np.random.rand() < 1000 / total_step:
        actions =  torch.clamp(torch.randn(action_shape), min = -1, max = 1)
    else:
        actions =  trainer.sample_action(current_obs.to(trainer.device))
        
    env.robots.set_joint_efforts(efforts = actions * env.motor_efforts)
    
    return actions

In [20]:
# observation
def get_obs(env):
    """
    Get robot states
    """
    
    # root position
    torso_position, torso_rotation  = env.robots.get_world_poses()
    torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])

    index = torch.LongTensor([1, 2, 3, 0])
    torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW
    
    up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]]
    forward_vec = quat_rotate(torso_rotation, torch.tensor([1.0, 0.0, 0.0]).repeat((env.num_envs, 1)))[...,[2]]
    
    # root velocity
    root_velocity = env.robots.get_velocities()
    velocity = root_velocity[:, 0:3]
    ang_velocity = env.angular_velocity_scale * root_velocity[:, 3:] # scaled
    
    # joint position and velocity
    dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]
    dof_vel = env.robots.get_joint_velocities() * env.dof_vel_scale # scaled
    
    # get obs
    obs = torch.cat([up_vec, forward_vec, torso_local_position, torso_rotation, velocity, ang_velocity, dof_pos, dof_vel], dim = 1)
    
    return obs

In [21]:
get_obs(env).shape

torch.Size([8, 57])

In [22]:
dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]

In [23]:
sit_position_target = torch.tensor([-0.1300, -1.3069,  0.1894,  0.1213,  0.0355,  0.1059,  0.2064, -0.7359,
        -0.7594,  0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800,
        -0.9257,  0.2923,  0.0162,  0.2884, -0.0267]).repeat(env.num_envs, 1)

In [24]:
# sit_position_target

In [25]:
# init root dist
torso_position, torso_rotation  = env.robots.get_world_poses()
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
target_local_position = torch.tensor([0.0, 0.9, -0.4]).repeat(env.num_envs, 1)


root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)

env.last_root_dist = root_dist

In [26]:
env.last_root_dist

tensor([0.2887, 0.2887, 0.2887, 0.2887, 0.2887, 0.2887, 0.2887, 0.2887])

In [27]:
# debug
# env.last_root_dist  = 0

In [28]:
sit_position_target[...,9:]

tensor([[ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.

In [29]:
def get_reward_done(env, verbose = False):
    # root position
    torso_position, torso_rotation  = env.robots.get_world_poses()
    index = torch.LongTensor([1, 2, 3, 0])
    torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW
    
    # get reward 
    torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
    target_local_position = torch.tensor([0.0, 0.8, -0.5]).repeat(env.num_envs, 1)
    
    root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)
    up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]].view(-1)
    
    joint_positions = env.robots.get_joint_positions() 
    joint_dist = torch.sum((joint_positions - sit_position_target)**2 / \
                           (env.joint_upper_limit - env.joint_lower_limit)**2
                           , dim = 1)
    
    root_velocity = torch.sum(env.robots.get_velocities()[...,:3]**2, dim = 1)
    
    # reward = torch.exp(-joint_dist) * up_vec  * torch.exp(- root_dist) * torch.exp(-root_velocity) 
    reward = torch.exp(-root_dist * 2) * torch.exp(-joint_dist) # * torch.exp(-root_velocity) 

    
    if verbose:
        print("reward", reward.tolist(), "; root_velocity: ", root_velocity.tolist(), "; joint_dist: ", joint_dist.tolist(), \
             "; root_dist: ", root_dist.tolist(), "; up_vec:", up_vec.tolist())
    
    # get done
    done = torch.where(torso_position[...,1] < 0.6, 1.0, 0.0)
    done = torch.where(env.progress_buf > 300, torch.ones(done.shape[0]), done)
    
    reward = torch.where(torso_position[...,1] < 0.7, -1.0, reward.double()).float()
    # done = torch.where(env.progress_buf > 300, 1.0, 0.0)
    
    
    
    return reward, done

In [30]:
get_reward_done(env, True)

reward [0.1274213343858719, 0.12742899358272552, 0.12742090225219727, 0.12742705643177032, 0.12742432951927185, 0.12742306292057037, 0.12742270529270172, 0.1274283528327942] ; root_velocity:  [0.03995088115334511, 0.04000934585928917, 0.039939213544130325, 0.040021687746047974, 0.04004756733775139, 0.040011946111917496, 0.039958853274583817, 0.040003418922424316] ; joint_dist:  [1.1392343044281006, 1.1391849517822266, 1.139235258102417, 1.1391987800598145, 1.1392252445220947, 1.1392239332199097, 1.1392292976379395, 1.139188528060913] ; root_dist:  [0.46051090955734253, 0.46050551533699036, 0.46051210165023804, 0.4605062007904053, 0.4605036973953247, 0.4605093002319336, 0.4605080485343933, 0.46050623059272766] ; up_vec: [0.9954283833503723, 0.9954266548156738, 0.9954292178153992, 0.9954266548156738, 0.9954260587692261, 0.9954272508621216, 0.9954279661178589, 0.9954270124435425]


(tensor([0.1274, 0.1274, 0.1274, 0.1274, 0.1274, 0.1274, 0.1274, 0.1274]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0.]))

In [31]:
# need to reset
def reset(done):
    if torch.sum(done) >= 1:
        env_ids = []
        for i in range(len(done)):
            if done[i] > 0:
                env_ids.append(i)
        # print("reset: ", env_ids)
        env.reset_idx(env_ids)

In [32]:
trainer = Trainer(57, 21, use_tensorboard=True)

In [33]:
trainer.add_env(env)

In [34]:
# trainer.policy.load_state_dict(torch.load("/home/yizhou/Research/Data/720_stand_latest.pth"))

In [35]:
total_step = 0 # reset 

In [36]:
for i in range(30000):
    total_step += 1
    
    # step
    current_obs = get_obs(env).clone()
    actions = step(env,trainer=trainer) # HAS TRAINER
    world.step(render=False)
    
    # continue

    # get obs
    new_obs = get_obs(env).clone()
    
    # get reward done
    reward, done = get_reward_done(env)
    env.reward_buf += reward
    # print(total_step, "reward, done", done)
    
    # reset
    reset(done)
    
    ## another step (controll frequency 1/30)
    # world.step(render=False)
    
    # buffer
    trainer.buf.add_batch(current_obs, actions, new_obs, reward, done)
    # print(total_step, "current_obs, actions, new_obs, reward, done \n\n", current_obs, actions, new_obs, reward, done)
    

    # debug
    if total_step % 1000 == 9:
        # env.reset_idx([0,1,2])
        print(total_step, "reward", torch.mean(reward).tolist(), torch.mean(env.reward_buf).tolist())
        print(total_step, "max Obs", torch.max(current_obs), torch.max(new_obs))
        world.render()
    
    # train
    if total_step > 2000:
        trainer.train(batch_size = 16)
        
        if total_step % 100 == 0:
            trainer.write_summary()
        
        if total_step % 10000 == 0:
            torch.save(trainer.policy.state_dict(), "/home/yizhou/Research/Data/720_sit_latest.pth")
  
    

9 reward 0.08471130579710007 0.4198840856552124
9 max Obs tensor(1.3612) tensor(1.4665)
1009 reward -0.07061770558357239 0.7223343849182129
1009 max Obs tensor(1.6633) tensor(1.3887)
p
[9.242s] [ext: omni.isaac.surface_gripper-0.1.2] startup
[9.247s] [ext: omni.kit.property.layer-1.1.2] startup
[9.248s] [ext: omni.isaac.range_sensor-0.4.2] startup
[9.277s] [ext: omni.graph.window.generic-1.3.8] startup
[9.279s] [ext: omni.isaac.utils-0.1.11] startup
[9.282s] [ext: omni.isaac.universal_robots-0.2.1] startup
[9.283s] [ext: omni.kit.property.audio-1.0.5] startup
[9.284s] [ext: omni.kit.property.skel-1.0.1] startup
[9.286s] [ext: omni.kit.property.render-1.1.0] startup
[9.287s] [ext: omni.kit.property.camera-1.0.3] startup
[9.288s] [ext: omni.kit.property.geometry-1.2.0] startup
[9.289s] [ext: omni.kit.property.light-1.0.5] startup
[9.291s] [ext: omni.kit.property.transform-1.0.2] startup
[9.294s] [ext: omni.isaac.occupancy_map-0.2.4] startup
[9.308s] [ext: omni.ui.scene-1.4.6] startup
[9.

In [ ]:
torch.mean(trainer.policy.loss_dict["critic"][-10:])

In [ ]:
world._physics_context.is_gpu_dynamics_enabled()

In [ ]:
world.step(render=True)

In [ ]:
world.render()

In [37]:
world.reset()
# env.reset_idx([_ for _ in range(8)])

In [38]:
env.reward_buf[[_ for _ in range(8)]] = 0

In [54]:
torch.save(trainer.policy.state_dict(), "/home/yizhou/Research/Data/720_sit_night.pth")

In [53]:
# test
for i in range(100):
    total_step += 1
    
    # step
    current_obs = get_obs(env).clone()
    actions, _, _, _  = trainer.policy.actor(current_obs.to(trainer.device), compute_pi=True, compute_log_pi=False)
    env.robots.set_joint_efforts(efforts = actions.cpu().data * env.motor_efforts)
    # print(actions)
    reward, done = get_reward_done(env, verbose=False)
    env.reward_buf += reward
    
    world.step(render=True)

tensor([[-0.1347, -0.2223,  0.0819, -0.2242,  0.1080, -0.0408, -0.0095, -0.1424,
          0.0459, -0.0561, -0.1626, -0.1309, -0.1383, -0.2596, -0.1037, -0.0061,
          0.2022,  0.0036, -0.1326, -0.1951,  0.1583],
        [-0.1871, -0.1899,  0.1743, -0.4740,  0.2733, -0.2778, -0.0190, -0.1893,
         -0.1855, -0.0497, -0.2588, -0.3081, -0.3042, -0.3537, -0.2111,  0.4099,
          0.4816,  0.0629, -0.1698, -0.2292,  0.1264],
        [-0.1899, -0.1852,  0.1756, -0.4712,  0.2780, -0.2747, -0.0152, -0.1962,
         -0.1918, -0.0503, -0.2499, -0.3115, -0.3045, -0.3447, -0.2114,  0.4101,
          0.4817,  0.0637, -0.1688, -0.2270,  0.1281],
        [-0.1990, -0.1841,  0.1803, -0.4694,  0.2749, -0.2632,  0.0026, -0.2133,
         -0.1954, -0.0515, -0.2230, -0.3254, -0.3081, -0.3351, -0.2029,  0.4054,
          0.4765,  0.0652, -0.1535, -0.2305,  0.1352],
        [-0.1409, -0.2255,  0.0898, -0.2320,  0.1135, -0.0330,  0.0015, -0.1496,
          0.0444, -0.0630, -0.1585, -0.1369, -0.139

tensor([[-0.1343, -0.2224,  0.0820, -0.2242,  0.1084, -0.0406, -0.0099, -0.1424,
          0.0455, -0.0564, -0.1619, -0.1306, -0.1379, -0.2584, -0.1045, -0.0056,
          0.2027,  0.0036, -0.1329, -0.1954,  0.1586],
        [-0.1859, -0.1909,  0.1718, -0.4799,  0.2715, -0.2839, -0.0192, -0.1832,
         -0.1827, -0.0493, -0.2716, -0.3074, -0.3037, -0.3669, -0.2100,  0.4134,
          0.4859,  0.0633, -0.1692, -0.2299,  0.1241],
        [-0.1897, -0.1876,  0.1744, -0.4690,  0.2748, -0.2714, -0.0142, -0.1937,
         -0.1877, -0.0501, -0.2513, -0.3094, -0.3026, -0.3469, -0.2098,  0.4038,
          0.4782,  0.0625, -0.1673, -0.2281,  0.1288],
        [-0.1964, -0.1862,  0.1795, -0.4733,  0.2744, -0.2688, -0.0006, -0.2091,
         -0.1924, -0.0506, -0.2317, -0.3233, -0.3091, -0.3423, -0.2035,  0.4103,
          0.4807,  0.0666, -0.1563, -0.2316,  0.1348],
        [-0.1406, -0.2260,  0.0879, -0.2316,  0.1115, -0.0311,  0.0021, -0.1477,
          0.0468, -0.0629, -0.1617, -0.1358, -0.138

tensor([[-0.1341, -0.2222,  0.0819, -0.2238,  0.1089, -0.0398, -0.0097, -0.1422,
          0.0448, -0.0562, -0.1620, -0.1305, -0.1374, -0.2590, -0.1051, -0.0064,
          0.2025,  0.0027, -0.1325, -0.1952,  0.1582],
        [-0.1849, -0.1894,  0.1726, -0.4757,  0.2755, -0.2792, -0.0206, -0.1866,
         -0.1869, -0.0491, -0.2639, -0.3060, -0.3031, -0.3555, -0.2127,  0.4124,
          0.4840,  0.0619, -0.1724, -0.2277,  0.1243],
        [-0.1883, -0.1884,  0.1740, -0.4741,  0.2759, -0.2778, -0.0174, -0.1902,
         -0.1878, -0.0497, -0.2599, -0.3090, -0.3044, -0.3542, -0.2115,  0.4096,
          0.4828,  0.0631, -0.1698, -0.2289,  0.1271],
        [-0.1939, -0.1873,  0.1798, -0.4752,  0.2766, -0.2720, -0.0040, -0.2057,
         -0.1930, -0.0497, -0.2372, -0.3206, -0.3089, -0.3443, -0.2065,  0.4144,
          0.4833,  0.0658, -0.1598, -0.2311,  0.1323],
        [-0.1403, -0.2236,  0.0881, -0.2252,  0.1131, -0.0254,  0.0020, -0.1517,
          0.0446, -0.0624, -0.1511, -0.1359, -0.138

tensor([[-1.3378e-01, -2.2181e-01,  8.2351e-02, -2.2640e-01,  1.1093e-01,
         -4.3018e-02, -1.1700e-02, -1.4200e-01,  4.3863e-02, -5.6131e-02,
         -1.6355e-01, -1.3088e-01, -1.3885e-01, -2.5945e-01, -1.0714e-01,
         -2.3137e-03,  2.0600e-01,  3.7968e-03, -1.3475e-01, -1.9539e-01,
          1.5832e-01],
        [-1.8453e-01, -1.9097e-01,  1.7203e-01, -4.7588e-01,  2.7397e-01,
         -2.8064e-01, -2.0747e-02, -1.8349e-01, -1.8320e-01, -4.8753e-02,
         -2.6868e-01, -3.0473e-01, -3.0261e-01, -3.6142e-01, -2.1255e-01,
          4.1119e-01,  4.8398e-01,  6.2505e-02, -1.7188e-01, -2.2859e-01,
          1.2433e-01],
        [-1.8822e-01, -1.8913e-01,  1.7336e-01, -4.7211e-01,  2.7532e-01,
         -2.7529e-01, -1.6323e-02, -1.9057e-01, -1.8631e-01, -4.9684e-02,
         -2.5826e-01, -3.0828e-01, -3.0318e-01, -3.5298e-01, -2.1105e-01,
          4.0680e-01,  4.8133e-01,  6.2581e-02, -1.6942e-01, -2.2856e-01,
          1.2745e-01],
        [-1.9491e-01, -1.8721e-01,  1.7866e

tensor([[-1.3356e-01, -2.2194e-01,  8.1413e-02, -2.2398e-01,  1.0905e-01,
         -4.0857e-02, -1.1265e-02, -1.4082e-01,  4.5106e-02, -5.5920e-02,
         -1.6332e-01, -1.2975e-01, -1.3779e-01, -2.5908e-01, -1.0506e-01,
         -6.5888e-03,  2.0279e-01,  2.7389e-03, -1.3375e-01, -1.9465e-01,
          1.5761e-01],
        [-1.8421e-01, -1.8972e-01,  1.7118e-01, -4.7408e-01,  2.7413e-01,
         -2.7964e-01, -2.1259e-02, -1.8454e-01, -1.8288e-01, -4.8345e-02,
         -2.6648e-01, -3.0449e-01, -3.0283e-01, -3.5872e-01, -2.1191e-01,
          4.1029e-01,  4.8289e-01,  6.3123e-02, -1.7266e-01, -2.2704e-01,
          1.2475e-01],
        [-1.8724e-01, -1.8981e-01,  1.7366e-01, -4.7478e-01,  2.7777e-01,
         -2.7900e-01, -1.6430e-02, -1.8977e-01, -1.8792e-01, -4.9548e-02,
         -2.6124e-01, -3.0797e-01, -3.0429e-01, -3.5511e-01, -2.1232e-01,
          4.1268e-01,  4.8532e-01,  6.3179e-02, -1.7129e-01, -2.2860e-01,
          1.2572e-01],
        [-1.9191e-01, -1.8774e-01,  1.7775e

tensor([[-0.1338, -0.2214,  0.0809, -0.2234,  0.1081, -0.0399, -0.0109, -0.1399,
          0.0449, -0.0559, -0.1640, -0.1299, -0.1368, -0.2602, -0.1042, -0.0079,
          0.2013,  0.0014, -0.1324, -0.1934,  0.1559],
        [-0.1824, -0.1918,  0.1709, -0.4755,  0.2735, -0.2819, -0.0244, -0.1792,
         -0.1822, -0.0483, -0.2738, -0.3016, -0.3015, -0.3633, -0.2137,  0.4111,
          0.4837,  0.0611, -0.1742, -0.2272,  0.1216],
        [-0.1879, -0.1874,  0.1727, -0.4690,  0.2761, -0.2727, -0.0165, -0.1917,
         -0.1878, -0.0492, -0.2557, -0.3074, -0.3024, -0.3483, -0.2110,  0.4051,
          0.4792,  0.0614, -0.1703, -0.2264,  0.1264],
        [-0.1925, -0.1888,  0.1775, -0.4753,  0.2736, -0.2754, -0.0049, -0.2016,
         -0.1877, -0.0481, -0.2436, -0.3186, -0.3089, -0.3508, -0.2043,  0.4148,
          0.4841,  0.0680, -0.1604, -0.2313,  0.1319],
        [-0.1375, -0.2210,  0.0873, -0.2263,  0.1136, -0.0272, -0.0012, -0.1451,
          0.0414, -0.0621, -0.1547, -0.1352, -0.138

tensor([[-0.1331, -0.2214,  0.0812, -0.2236,  0.1099, -0.0401, -0.0119, -0.1406,
          0.0446, -0.0557, -0.1632, -0.1295, -0.1378, -0.2588, -0.1059, -0.0078,
          0.2024,  0.0021, -0.1342, -0.1943,  0.1578],
        [-0.1831, -0.1891,  0.1697, -0.4669,  0.2728, -0.2731, -0.0239, -0.1830,
         -0.1825, -0.0489, -0.2631, -0.3000, -0.2987, -0.3507, -0.2125,  0.4020,
          0.4758,  0.0598, -0.1745, -0.2244,  0.1230],
        [-0.1864, -0.1898,  0.1705, -0.4691,  0.2717, -0.2752, -0.0201, -0.1857,
         -0.1820, -0.0490, -0.2630, -0.3044, -0.3022, -0.3549, -0.2096,  0.4020,
          0.4775,  0.0618, -0.1713, -0.2268,  0.1257],
        [-0.1904, -0.1892,  0.1773, -0.4773,  0.2761, -0.2775, -0.0052, -0.2009,
         -0.1900, -0.0472, -0.2442, -0.3182, -0.3089, -0.3498, -0.2052,  0.4212,
          0.4885,  0.0689, -0.1619, -0.2295,  0.1301],
        [-0.1342, -0.2203,  0.0864, -0.2314,  0.1149, -0.0305, -0.0050, -0.1382,
          0.0402, -0.0615, -0.1620, -0.1344, -0.140

tensor([[-0.1327, -0.2203,  0.0810, -0.2253,  0.1109, -0.0430, -0.0147, -0.1392,
          0.0438, -0.0557, -0.1670, -0.1290, -0.1389, -0.2613, -0.1078, -0.0071,
          0.2035,  0.0021, -0.1361, -0.1941,  0.1568],
        [-0.1809, -0.1899,  0.1706, -0.4691,  0.2764, -0.2763, -0.0280, -0.1808,
         -0.1839, -0.0480, -0.2667, -0.2982, -0.3000, -0.3513, -0.2160,  0.4066,
          0.4794,  0.0592, -0.1787, -0.2238,  0.1213],
        [-0.1857, -0.1887,  0.1718, -0.4729,  0.2777, -0.2780, -0.0192, -0.1876,
         -0.1867, -0.0485, -0.2628, -0.3058, -0.3037, -0.3542, -0.2125,  0.4103,
          0.4836,  0.0625, -0.1734, -0.2265,  0.1251],
        [-0.1896, -0.1890,  0.1764, -0.4757,  0.2743, -0.2782, -0.0079, -0.1979,
         -0.1886, -0.0476, -0.2472, -0.3157, -0.3078, -0.3502, -0.2052,  0.4190,
          0.4861,  0.0686, -0.1634, -0.2296,  0.1293],
        [-0.1313, -0.2185,  0.0843, -0.2363,  0.1154, -0.0321, -0.0050, -0.1324,
          0.0399, -0.0609, -0.1693, -0.1344, -0.142

tensor([[-0.1316, -0.2219,  0.0810, -0.2312,  0.1103, -0.0483, -0.0165, -0.1337,
          0.0444, -0.0553, -0.1754, -0.1291, -0.1403, -0.2694, -0.1073, -0.0008,
          0.2079,  0.0020, -0.1368, -0.1945,  0.1536],
        [-0.1804, -0.1895,  0.1690, -0.4718,  0.2761, -0.2782, -0.0286, -0.1777,
         -0.1836, -0.0479, -0.2739, -0.2976, -0.2990, -0.3579, -0.2159,  0.4069,
          0.4807,  0.0577, -0.1785, -0.2237,  0.1194],
        [-0.1832, -0.1923,  0.1701, -0.4768,  0.2728, -0.2842, -0.0254, -0.1785,
         -0.1810, -0.0491, -0.2767, -0.3017, -0.3028, -0.3654, -0.2126,  0.4103,
          0.4851,  0.0627, -0.1756, -0.2292,  0.1236],
        [-0.1891, -0.1893,  0.1759, -0.4732,  0.2742, -0.2753, -0.0070, -0.1977,
         -0.1884, -0.0474, -0.2447, -0.3147, -0.3064, -0.3475, -0.2048,  0.4168,
          0.4842,  0.0678, -0.1628, -0.2282,  0.1286],
        [-0.1282, -0.2144,  0.0847, -0.2403,  0.1201, -0.0350, -0.0071, -0.1312,
          0.0355, -0.0596, -0.1682, -0.1357, -0.145

tensor([[-0.1315, -0.2207,  0.0818, -0.2338,  0.1132, -0.0509, -0.0156, -0.1356,
          0.0423, -0.0541, -0.1742, -0.1307, -0.1419, -0.2694, -0.1090,  0.0056,
          0.2125,  0.0031, -0.1369, -0.1951,  0.1542],
        [-0.1783, -0.1937,  0.1674, -0.4765,  0.2718, -0.2847, -0.0312, -0.1691,
         -0.1762, -0.0481, -0.2882, -0.2945, -0.2988, -0.3728, -0.2149,  0.4078,
          0.4837,  0.0589, -0.1789, -0.2270,  0.1190],
        [-0.1834, -0.1914,  0.1707, -0.4700,  0.2739, -0.2766, -0.0241, -0.1810,
         -0.1827, -0.0488, -0.2684, -0.3004, -0.3005, -0.3561, -0.2130,  0.4044,
          0.4794,  0.0599, -0.1749, -0.2267,  0.1231],
        [-0.1888, -0.1922,  0.1745, -0.4762,  0.2713, -0.2783, -0.0091, -0.1933,
         -0.1836, -0.0470, -0.2551, -0.3133, -0.3070, -0.3584, -0.2047,  0.4144,
          0.4843,  0.0663, -0.1633, -0.2309,  0.1283],
        [-0.1252, -0.2110,  0.0860, -0.2423,  0.1270, -0.0350, -0.0028, -0.1358,
          0.0288, -0.0586, -0.1556, -0.1401, -0.146

tensor([[-0.1298, -0.2201,  0.0807, -0.2337,  0.1149, -0.0521, -0.0164, -0.1371,
          0.0414, -0.0542, -0.1710, -0.1308, -0.1414, -0.2663, -0.1098,  0.0085,
          0.2139,  0.0041, -0.1385, -0.1929,  0.1536],
        [-0.1780, -0.1922,  0.1678, -0.4745,  0.2758, -0.2820, -0.0306, -0.1727,
         -0.1777, -0.0464, -0.2835, -0.2950, -0.2999, -0.3683, -0.2164,  0.4076,
          0.4835,  0.0585, -0.1802, -0.2249,  0.1200],
        [-0.1828, -0.1905,  0.1701, -0.4724,  0.2758, -0.2788, -0.0243, -0.1801,
         -0.1829, -0.0481, -0.2732, -0.3005, -0.3010, -0.3609, -0.2142,  0.4063,
          0.4818,  0.0600, -0.1755, -0.2264,  0.1229],
        [-0.1890, -0.1912,  0.1746, -0.4696,  0.2719, -0.2718, -0.0068, -0.1975,
         -0.1839, -0.0469, -0.2449, -0.3128, -0.3055, -0.3485, -0.2040,  0.4104,
          0.4803,  0.0664, -0.1629, -0.2284,  0.1295],
        [-0.1214, -0.2111,  0.0813, -0.2345,  0.1227, -0.0284, -0.0040, -0.1331,
          0.0314, -0.0588, -0.1505, -0.1368, -0.143

tensor([[-0.1299, -0.2192,  0.0792, -0.2232,  0.1102, -0.0434, -0.0147, -0.1387,
          0.0433, -0.0549, -0.1621, -0.1283, -0.1374, -0.2569, -0.1061, -0.0056,
          0.2027,  0.0030, -0.1369, -0.1920,  0.1542],
        [-0.1764, -0.1940,  0.1664, -0.4769,  0.2718, -0.2871, -0.0347, -0.1665,
         -0.1733, -0.0474, -0.2929, -0.2918, -0.2993, -0.3757, -0.2156,  0.4082,
          0.4844,  0.0595, -0.1821, -0.2271,  0.1192],
        [-0.1833, -0.1890,  0.1689, -0.4663,  0.2754, -0.2724, -0.0224, -0.1841,
         -0.1825, -0.0479, -0.2637, -0.3002, -0.3005, -0.3514, -0.2120,  0.4012,
          0.4769,  0.0595, -0.1755, -0.2238,  0.1241],
        [-0.1849, -0.1953,  0.1730, -0.4825,  0.2700, -0.2882, -0.0160, -0.1838,
         -0.1802, -0.0468, -0.2723, -0.3089, -0.3081, -0.3706, -0.2058,  0.4209,
          0.4896,  0.0671, -0.1689, -0.2323,  0.1252],
        [-0.1181, -0.2128,  0.0759, -0.2214,  0.1131, -0.0110, -0.0029, -0.1277,
          0.0383, -0.0591, -0.1490, -0.1300, -0.139

tensor([[-0.1286, -0.2177,  0.0786, -0.2176,  0.1099, -0.0397, -0.0168, -0.1381,
          0.0434, -0.0539, -0.1588, -0.1263, -0.1374, -0.2519, -0.1059, -0.0134,
          0.1967,  0.0024, -0.1384, -0.1905,  0.1543],
        [-0.1756, -0.1938,  0.1656, -0.4752,  0.2726, -0.2847, -0.0343, -0.1661,
         -0.1730, -0.0464, -0.2922, -0.2910, -0.2984, -0.3750, -0.2156,  0.4065,
          0.4834,  0.0578, -0.1820, -0.2246,  0.1177],
        [-0.1807, -0.1919,  0.1691, -0.4725,  0.2751, -0.2805, -0.0276, -0.1768,
         -0.1798, -0.0476, -0.2779, -0.2976, -0.3011, -0.3635, -0.2142,  0.4066,
          0.4823,  0.0600, -0.1784, -0.2263,  0.1225],
        [-0.1869, -0.1916,  0.1740, -0.4703,  0.2720, -0.2747, -0.0088, -0.1936,
         -0.1836, -0.0470, -0.2502, -0.3100, -0.3039, -0.3509, -0.2049,  0.4133,
          0.4819,  0.0668, -0.1645, -0.2283,  0.1278],
        [-0.1200, -0.1979,  0.0786, -0.1966,  0.1215,  0.0135,  0.0060, -0.1468,
          0.0267, -0.0522, -0.1083, -0.1350, -0.139

tensor([[-1.2734e-01, -2.1558e-01,  7.6840e-02, -2.2169e-01,  1.0681e-01,
         -4.3671e-02, -1.9783e-02, -1.3172e-01,  4.3939e-02, -5.2850e-02,
         -1.6938e-01, -1.2411e-01, -1.3769e-01, -2.6224e-01, -1.0528e-01,
         -1.5112e-02,  1.9682e-01, -6.1941e-04, -1.3788e-01, -1.9213e-01,
          1.5038e-01],
        [-1.7347e-01, -1.9543e-01,  1.6494e-01, -4.7975e-01,  2.7154e-01,
         -2.9184e-01, -3.9820e-02, -1.5964e-01, -1.7051e-01, -4.6339e-02,
         -3.0373e-01, -2.8817e-01, -2.9961e-01, -3.8364e-01, -2.1687e-01,
          4.1007e-01,  4.8663e-01,  5.8130e-02, -1.8577e-01, -2.2652e-01,
          1.1611e-01],
        [-1.7995e-01, -1.9222e-01,  1.6777e-01, -4.7262e-01,  2.7356e-01,
         -2.8169e-01, -2.9011e-02, -1.7470e-01, -1.7673e-01, -4.6876e-02,
         -2.8162e-01, -2.9645e-01, -3.0126e-01, -3.6777e-01, -2.1382e-01,
          4.0488e-01,  4.8161e-01,  5.9752e-02, -1.7862e-01, -2.2613e-01,
          1.2204e-01],
        [-1.8690e-01, -1.9266e-01,  1.7294e

tensor([[-1.2671e-01, -2.1407e-01,  7.7832e-02, -2.2868e-01,  1.1125e-01,
         -4.9745e-02, -2.0597e-02, -1.2999e-01,  4.0615e-02, -5.1040e-02,
         -1.7298e-01, -1.2695e-01, -1.4134e-01, -2.6694e-01, -1.0731e-01,
         -2.6330e-03,  2.0525e-01,  1.2798e-04, -1.3838e-01, -1.9081e-01,
          1.4759e-01],
        [-1.7316e-01, -1.9522e-01,  1.6486e-01, -4.8077e-01,  2.7395e-01,
         -2.9198e-01, -3.7760e-02, -1.6064e-01, -1.7128e-01, -4.6050e-02,
         -3.0366e-01, -2.8883e-01, -2.9961e-01, -3.8495e-01, -2.1748e-01,
          4.1247e-01,  4.8853e-01,  5.8604e-02, -1.8536e-01, -2.2560e-01,
          1.1608e-01],
        [-1.7831e-01, -1.9423e-01,  1.6728e-01, -4.7594e-01,  2.7286e-01,
         -2.8496e-01, -3.1574e-02, -1.6932e-01, -1.7591e-01, -4.7588e-02,
         -2.8985e-01, -2.9413e-01, -3.0003e-01, -3.7357e-01, -2.1470e-01,
          4.0713e-01,  4.8412e-01,  5.8343e-02, -1.8031e-01, -2.2683e-01,
          1.1940e-01],
        [-1.8516e-01, -1.9448e-01,  1.7213e

tensor([[-0.1254, -0.2126,  0.0787, -0.2315,  0.1151, -0.0529, -0.0203, -0.1293,
          0.0371, -0.0504, -0.1712, -0.1291, -0.1430, -0.2659, -0.1090,  0.0077,
          0.2110,  0.0017, -0.1383, -0.1887,  0.1458],
        [-0.1724, -0.1963,  0.1635, -0.4781,  0.2714, -0.2893, -0.0386, -0.1589,
         -0.1680, -0.0459, -0.3039, -0.2866, -0.2980, -0.3847, -0.2162,  0.4075,
          0.4854,  0.0571, -0.1854, -0.2252,  0.1158],
        [-0.1780, -0.1931,  0.1672, -0.4701,  0.2737, -0.2795, -0.0315, -0.1724,
         -0.1759, -0.0470, -0.2814, -0.2929, -0.2992, -0.3644, -0.2147,  0.4026,
          0.4799,  0.0582, -0.1811, -0.2249,  0.1210],
        [-0.1860, -0.1922,  0.1729, -0.4695,  0.2716, -0.2749, -0.0099, -0.1929,
         -0.1808, -0.0462, -0.2518, -0.3091, -0.3046, -0.3528, -0.2046,  0.4120,
          0.4817,  0.0671, -0.1655, -0.2277,  0.1282],
        [-0.1152, -0.1936,  0.0784, -0.2176,  0.1287, -0.0166, -0.0073, -0.1380,
          0.0205, -0.0503, -0.1286, -0.1358, -0.148

tensor([[-0.1243, -0.2097,  0.0782, -0.2264,  0.1146, -0.0478, -0.0178, -0.1320,
          0.0350, -0.0504, -0.1614, -0.1298, -0.1419, -0.2575, -0.1071,  0.0071,
          0.2082,  0.0022, -0.1360, -0.1867,  0.1466],
        [-0.1709, -0.1972,  0.1628, -0.4782,  0.2719, -0.2897, -0.0401, -0.1568,
         -0.1669, -0.0456, -0.3072, -0.2843, -0.2973, -0.3866, -0.2169,  0.4075,
          0.4856,  0.0560, -0.1871, -0.2248,  0.1148],
        [-0.1771, -0.1927,  0.1673, -0.4764,  0.2763, -0.2857, -0.0320, -0.1707,
         -0.1768, -0.0465, -0.2903, -0.2941, -0.3007, -0.3737, -0.2164,  0.4096,
          0.4860,  0.0592, -0.1821, -0.2259,  0.1205],
        [-0.1838, -0.1935,  0.1728, -0.4776,  0.2736, -0.2834, -0.0141, -0.1868,
         -0.1814, -0.0457, -0.2663, -0.3078, -0.3060, -0.3646, -0.2078,  0.4194,
          0.4883,  0.0665, -0.1687, -0.2296,  0.1258],
        [-0.1167, -0.1924,  0.0788, -0.2089,  0.1273, -0.0069, -0.0028, -0.1434,
          0.0210, -0.0500, -0.1164, -0.1362, -0.146

tensor([[-0.1210, -0.2114,  0.0729, -0.2177,  0.1045, -0.0340, -0.0135, -0.1243,
          0.0414, -0.0520, -0.1632, -0.1235, -0.1361, -0.2626, -0.0986, -0.0175,
          0.1920, -0.0041, -0.1289, -0.1868,  0.1466],
        [-0.1683, -0.1993,  0.1615, -0.4816,  0.2718, -0.2935, -0.0423, -0.1512,
         -0.1650, -0.0454, -0.3170, -0.2814, -0.2963, -0.3943, -0.2174,  0.4108,
          0.4885,  0.0543, -0.1891, -0.2241,  0.1114],
        [-0.1760, -0.1924,  0.1665, -0.4710,  0.2755, -0.2813, -0.0318, -0.1711,
         -0.1775, -0.0470, -0.2842, -0.2918, -0.2977, -0.3650, -0.2151,  0.4077,
          0.4827,  0.0580, -0.1823, -0.2225,  0.1183],
        [-0.1831, -0.1955,  0.1714, -0.4764,  0.2706, -0.2831, -0.0155, -0.1840,
         -0.1784, -0.0466, -0.2694, -0.3055, -0.3045, -0.3664, -0.2065,  0.4169,
          0.4866,  0.0656, -0.1695, -0.2294,  0.1245],
        [-0.1155, -0.1925,  0.0787, -0.2139,  0.1283, -0.0136, -0.0058, -0.1410,
          0.0199, -0.0501, -0.1220, -0.1362, -0.147

tensor([[-1.1793e-01, -2.1082e-01,  7.1524e-02, -2.2259e-01,  1.0576e-01,
         -3.2597e-02, -1.2705e-02, -1.1906e-01,  4.0921e-02, -4.9561e-02,
         -1.6850e-01, -1.2437e-01, -1.3998e-01, -2.7301e-01, -9.6920e-02,
         -1.7922e-02,  1.9361e-01, -7.4805e-03, -1.2669e-01, -1.8692e-01,
          1.4568e-01],
        [-1.6635e-01, -2.0071e-01,  1.6024e-01, -4.8270e-01,  2.7212e-01,
         -2.9455e-01, -4.2108e-02, -1.5003e-01, -1.6278e-01, -4.5340e-02,
         -3.2109e-01, -2.7960e-01, -2.9578e-01, -3.9815e-01, -2.1669e-01,
          4.1242e-01,  4.9006e-01,  5.3891e-02, -1.9020e-01, -2.2380e-01,
          1.1123e-01],
        [-1.7459e-01, -1.9394e-01,  1.6557e-01, -4.7277e-01,  2.7356e-01,
         -2.8432e-01, -3.6702e-02, -1.6548e-01, -1.7267e-01, -4.5910e-02,
         -2.9347e-01, -2.8868e-01, -2.9874e-01, -3.7315e-01, -2.1608e-01,
          4.0436e-01,  4.8210e-01,  5.7428e-02, -1.8472e-01, -2.2480e-01,
          1.1889e-01],
        [-1.8277e-01, -1.9464e-01,  1.7107e

In [45]:
print(total_step, "reward", torch.mean(reward).tolist(), env.reward_buf.tolist())

30301 reward -0.48842620849609375 [-93.01312255859375, 15.426419258117676, 15.442214012145996, 15.661898612976074, -90.72761535644531, -88.83724212646484, 15.403840065002441, -99.05352020263672]


In [50]:
world.reset()

In [ ]:
# trainer.policy.actor(current_obs.cuda())

# Debug

In [ ]:
world.reset()

In [ ]:
total_step = 0

In [ ]:
for debug in range(30):
    # step
    current_obs = get_obs(env).clone()
    actions = step(env,trainer=trainer) # HAS TRAINER
    # print(actions)
    world.step(render=True)

In [ ]:
env.reset_idx([1])
# env.reset()
# world.step(render=True)

In [ ]:
world.step(render=True)

In [ ]:
get_obs(env)[1]

In [ ]:

torso_position, torso_rotation  = env.robots.get_world_poses()
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])

index = torch.LongTensor([1, 2, 3, 0])
torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW

up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]]
forward_vec = quat_rotate(torso_rotation, torch.tensor([1.0, 0.0, 0.0]).repeat((env.num_envs, 1)))[...,[2]]

# root velocity
root_velocity = env.robots.get_velocities()
velocity = root_velocity[:, 0:3]
ang_velocity = env.angular_velocity_scale * root_velocity[:, 3:] # scaled

# joint position and velocity
dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]
dof_vel = env.robots.get_joint_velocities() * env.dof_vel_scale # scaled

# get obs
obs = torch.cat([up_vec, forward_vec, torso_local_position, torso_rotation, velocity, ang_velocity, dof_pos, dof_vel], dim = 1)


In [ ]:
torso_local_position[1]

In [ ]:
torso_rotation[1]

In [ ]:
velocity[1]

In [ ]:
ang_velocity[1]

In [ ]:
env.robots.get_joint_positions()[1]

In [ ]:
dof_vel[1]

In [ ]:
env.robots._physics_view.get_root_velocities()[1]

In [ ]:
# env.robots._default_state

In [ ]:
dof_pos[1]

In [ ]:
torso_local_position

In [ ]:
# root position
torso_position, torso_rotation  = env.robots.get_world_poses()
index = torch.LongTensor([1, 2, 3, 0])
torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW

# get reward 
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
target_local_position = torch.tensor([0.0, 0.9, -0.4]).repeat(env.num_envs, 1)

root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)
up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]].view(-1)

joint_positions = env.robots.get_joint_positions() 
joint_dist = torch.sum((joint_positions - sit_position_target)**2 / (env.joint_upper_limit - env.joint_lower_limit)**2, \
                       dim = 1)

root_velocity = torch.sum(env.robots.get_velocities()[...,:3]**2, dim = 1)

# reward = torch.exp(-joint_dist) * up_vec  * torch.exp(-root_dist) * torch.exp(-root_velocity) 
reward = up_vec  * torch.exp(-root_dist * 5) * torch.exp(-joint_dist)


In [ ]:
get_reward_done(env, True)

In [ ]:
joint_positions- sit_position_target

In [ ]:
sit_position_target

In [ ]:
env.robots.get_joint_positions()[0]

In [ ]:
sit_position_target[0]

In [ ]:
env.robots.set_joint_positions(sit_position_target)

In [ ]:
world.step(render=True)