In [1]:
from rl.torch_utils import *
from rl.torch_jit_utils import *
from rl.trainer import Trainer

# trainer = Trainer(57, 21)

In [2]:
import getpass

user = getpass.getuser()

In [3]:
user

'yizhou'

In [4]:
from omni.isaac.kit import SimulationApp

simulation_app = SimulationApp({"headless": True, "open_usd": f"omniverse://localhost/Users/{user}/test_humanoid_sit.usd", 
                                "livesync_usd": f"omniverse://localhost/Users/{user}/test_humanoid_sit.usd"})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-2759bf24-939d-49f0-88f5-69da2fe379f6.json

OmniAssetFileFormat


[2.040s] [ext: omni.mdl-0.1.0] startup
[2.067s] [ext: omni.kit.menu.create-1.0.2] startup
[2.069s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[2.070s] [ext: omni.kit.window.drop_support-1.0.0] startup
[2.072s] [ext: omni.kit.material.library-1.3.10] startup
[2.075s] [ext: omni.kit.window.property-1.6.3] startup
[2.078s] [ext: omni.kit.context_menu-1.3.9] startup
[2.083s] [ext: omni.kit.window.file_importer-1.0.4] startup
[2.084s] [ext: omni.kit.stage_templates-1.1.2] startup
[2.087s] [ext: omni.kit.widget.stage-2.6.15] startup
[2.093s] [ext: omni.kit.window.file-1.3.16] startup
[2.096s] [ext: omni.debugdraw-0.1.0] startup
[2.104s] [ext: omni.kit.window.content_browser-2.4.28] startup
[2.118s] [ext: omni.kit.widget.prompt-1.0.1] startup
[2.119s] [ext: omni.kit.property.usd-3.14.8] startup
[2.158s] [ext: omni.hydra.engine.stats-1.0.0] startup
[2.166s] [ext: omni.kit.widget.settings-1.0.0] startup
[2.168s] [ext: omni.graph.tools-1.3.5] startup
[2.198s] [ext: omni.graph.core-2.27.0

2022-07-21 04:52:37 [2,461ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-21 04:52:37 [2,462ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


Warp initialized:
   Version: 0.2.1
   Using CUDA device: NVIDIA GeForce RTX 3090
   Using CPU compiler: /usr/bin/g++
[7.657s] [ext: omni.kit.window.preferences-1.2.1] startup
[7.696s] [ext: omni.kit.ui_test-1.2.0] startup
[7.699s] [ext: omni.graph.ui-1.6.1] startup
[7.735s] [ext: omni.kvdb-0.0.0] startup
[7.740s] [ext: omni.kit.widget.searchfield-1.0.6] startup
[7.742s] [ext: omni.convexdecomposition-1.4.12] startup
[7.746s] [ext: omni.graph.action-1.17.0] startup
[7.763s] [ext: omni.localcache-0.0.0] startup
[7.768s] [ext: omni.usdphysics-1.4.12] startup
[7.771s] [ext: omni.graph.scriptnode-0.5.0] startup
[7.776s] [ext: omni.physx-1.4.12-5.1] startup
2022-07-21 04:52:42 [7,789ms] [Warning] [omni.kvdb.plugin] wasn't able to load the meta database, trying to repair it ...
2022-07-21 04:52:42 [7,846ms] [Warning] [omni.kvdb.plugin] repair failed
[7.858s] [ext: omni.kit.usd_undo-0.1.0] startup
[7.861s] [ext: omni.graph.nodes-1.25.0] startup
[7.887s] [ext: omni.physx.commands-1.4.12-5.1] s

In [5]:
import omni
from omni.isaac.core import World
from pxr import Gf, Sdf, UsdGeom, UsdShade

import torch
import numpy as np

In [6]:
world = World(physics_dt= 1.0 / 60, backend = "torch")

In [7]:
from omni.isaac.core.utils.stage import set_stage_up_axis

set_stage_up_axis("y")
world.get_physics_context().set_gravity(-9.81)

In [8]:
from omni.isaac.core.utils.stage import get_current_stage
UsdGeom.GetStageUpAxis(get_current_stage())

'Y'

In [9]:
world.get_physics_context()._physics_scene.GetGravityDirectionAttr().Get()

Gf.Vec3f(0.0, -1.0, 0.0)

In [10]:
# world.scene.add_default_ground_plane()

In [11]:
# get prims
len(list(world.scene.stage.TraverseAll()))

856

In [12]:
world.render()

In [13]:
from rl.robot_env import RobotEnv

env = RobotEnv("/World/envs/*/humanoid/torso")

In [14]:
world.render()

In [15]:
world.reset()

In [16]:
env.start()

simlation context torch None
num_envs 8
default joint state tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]) tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],

In [17]:
world.scene.add(env.robots)

In [18]:
total_step = 0

In [19]:
# step
def step(env, trainer, warm_up_steps = 2000):
    # action shape
    action_shape = env.action_shape
    
    # env step
    env.progress_buf += 1
    if total_step < warm_up_steps or np.random.rand() < 1000 / total_step:
        actions =  (2 * torch.rand(action_shape) - 1) / 10
    elif np.random.rand() < 1000 / total_step:
        actions =  (2 * torch.rand(action_shape) - 1)
    else:
        actions =  trainer.sample_action(current_obs.to(trainer.device))
        
    env.robots.set_joint_efforts(efforts = actions * env.motor_efforts)
    
    return actions

In [20]:
# observation
def get_obs(env):
    """
    Get robot states
    """
    
    # root position
    torso_position, torso_rotation  = env.robots.get_world_poses()
    torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])

    index = torch.LongTensor([1, 2, 3, 0])
    torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW
    
    up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]]
    forward_vec = quat_rotate(torso_rotation, torch.tensor([1.0, 0.0, 0.0]).repeat((env.num_envs, 1)))[...,[2]]
    
    # root velocity
    root_velocity = env.robots.get_velocities()
    velocity = root_velocity[:, 0:3]
    ang_velocity = env.angular_velocity_scale * root_velocity[:, 3:] # scaled
    
    # joint position and velocity
    dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]
    dof_vel = env.robots.get_joint_velocities() * env.dof_vel_scale # scaled
    
    # get obs
    obs = torch.cat([up_vec, forward_vec, torso_local_position, torso_rotation, velocity, ang_velocity, dof_pos, dof_vel], dim = 1)
    
    return obs

In [21]:
get_obs(env).shape

torch.Size([8, 57])

In [22]:
dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]

In [23]:
sit_position_target = torch.tensor([-0.1300, -1.3069,  0.1894,  0.1213,  0.0355,  0.1059,  0.2064, -0.7359,
        -0.7594,  0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800,
        -0.9257,  0.2923,  0.0162,  0.2884, -0.0267]).repeat(env.num_envs, 1)

In [24]:
# sit_position_target

In [25]:
# init root dist
torso_position, torso_rotation  = env.robots.get_world_poses()
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
target_local_position = torch.tensor([0.0, 0.9, -0.4]).repeat(env.num_envs, 1)


root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)

env.last_root_dist = root_dist

In [26]:
env.last_root_dist

tensor([0.2910, 0.2910, 0.2910, 0.2910, 0.2910, 0.2910, 0.2910, 0.2910])

In [27]:
# debug
# env.last_root_dist  = 0

In [28]:
sit_position_target[...,9:]

tensor([[ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.2884, -0.0267],
        [ 0.0979, -0.7716,  0.0067, -0.0837, -0.7800, -0.0659, -0.8800, -0.9257,
          0.2923,  0.0162,  0.

In [29]:
def get_reward_done(env, verbose = False):
    # root position
    torso_position, torso_rotation  = env.robots.get_world_poses()
    index = torch.LongTensor([1, 2, 3, 0])
    torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW
    
    # get reward 
    torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
    target_local_position = torch.tensor([0.0, 0.8, -0.5]).repeat(env.num_envs, 1)
    
    root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)
    up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]].view(-1)
    
    joint_positions = env.robots.get_joint_positions() 
    joint_dist = torch.sum((joint_positions - sit_position_target)**2 / \
                           (env.joint_upper_limit - env.joint_lower_limit)**2
                           , dim = 1)
    
    root_velocity = torch.sum(env.robots.get_velocities()[...,:3]**2, dim = 1)
    
    # reward = torch.exp(-joint_dist) * up_vec  * torch.exp(- root_dist) * torch.exp(-root_velocity) 
    reward = torch.exp(-root_dist * 2) * torch.exp(-joint_dist) # * torch.exp(-root_velocity) 

    
    if verbose:
        print("reward", reward.tolist(), "; root_velocity: ", root_velocity.tolist(), "; joint_dist: ", joint_dist.tolist(), \
             "; root_dist: ", root_dist.tolist(), "; up_vec:", up_vec.tolist())
    
    # get done
    done = torch.where(torso_position[...,1] < 0.6, 1.0, 0.0)
    done = torch.where(env.progress_buf > 300, torch.ones(done.shape[0]), done)
    
    reward = torch.where(torso_position[...,1] < 0.7, -1.0, reward.double()).float()
    # done = torch.where(env.progress_buf > 300, 1.0, 0.0)
    
    
    
    return reward, done

In [30]:
get_reward_done(env, True)

reward [0.1264093965291977, 0.12640942633152008, 0.12641264498233795, 0.1264093518257141, 0.12640909850597382, 0.1264084428548813, 0.12641331553459167, 0.12641021609306335] ; root_velocity:  [0.005010411608964205, 0.005008046515285969, 0.004997488111257553, 0.005019723903387785, 0.005025562830269337, 0.004997221287339926, 0.005026194266974926, 0.00502060679718852] ; joint_dist:  [1.1415057182312012, 1.1415084600448608, 1.141480565071106, 1.1415098905563354, 1.1415107250213623, 1.1415139436721802, 1.1414793729782104, 1.1415038108825684] ; root_dist:  [0.4633618891239166, 0.46336036920547485, 0.46336159110069275, 0.4633600115776062, 0.4633605480194092, 0.4633615016937256, 0.4633595943450928, 0.4633595943450928] ; up_vec: [0.9993165135383606, 0.9993165731430054, 0.9993168115615845, 0.9993167519569397, 0.9993163347244263, 0.9993165731430054, 0.9993165731430054, 0.9993164539337158]


(tensor([0.1264, 0.1264, 0.1264, 0.1264, 0.1264, 0.1264, 0.1264, 0.1264]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0.]))

In [31]:
# need to reset
def reset(done):
    if torch.sum(done) >= 1:
        env_ids = []
        for i in range(len(done)):
            if done[i] > 0:
                env_ids.append(i)
        # print("reset: ", env_ids)
        env.reset_idx(env_ids)

In [32]:
trainer = Trainer(57, 21, use_tensorboard=True)

In [33]:
trainer.add_env(env)

In [34]:
# trainer.policy.load_state_dict(torch.load("/home/yizhou/Research/Data/720_stand_latest.pth"))

In [35]:
total_step = 0 # reset 

In [ ]:
for i in range(30000):
    total_step += 1
    
    # step
    current_obs = get_obs(env).clone()
    actions = step(env,trainer=trainer) # HAS TRAINER
    world.step(render=False)
    
    # continue

    # get obs
    new_obs = get_obs(env).clone()
    
    # get reward done
    reward, done = get_reward_done(env)
    env.reward_buf += reward
    # print(total_step, "reward, done", done)
    
    # reset
    reset(done)
    
    ## another step (controll frequency 1/30)
    # world.step(render=False)
    
    # buffer
    trainer.buf.add_batch(current_obs, actions, new_obs, reward, done)
    # print(total_step, "current_obs, actions, new_obs, reward, done \n\n", current_obs, actions, new_obs, reward, done)
    

    # debug
    if total_step % 1000 == 9:
        # env.reset_idx([0,1,2])
        print(total_step, "reward", torch.mean(reward).tolist(), torch.mean(env.reward_buf).tolist())
        print(total_step, "max Obs", torch.max(current_obs), torch.max(new_obs))
        world.render()
    
    # train
    if total_step > 2000:
        trainer.train(batch_size = 16)
        
        if total_step % 100 == 0:
            trainer.write_summary()
        
        if total_step % 10000 == 0:
            torch.save(trainer.policy.state_dict(), "/home/yizhou/Research/Data/720_sit_latest.pth")
    
    

9 reward 0.04883845895528793 0.46894288063049316
9 max Obs tensor(2.1577) tensor(1.8839)
1009 reward -0.29572466015815735 0.20444411039352417
1009 max Obs tensor(1.2612) tensor(1.2609)
s] [ext: omni.kit.widget.live-0.1.0] startup
[10.567s] [ext: omni.isaac.surface_gripper-0.1.2] startup
[10.578s] [ext: omni.kit.property.layer-1.1.2] startup
[10.582s] [ext: omni.isaac.range_sensor-0.4.2] startup
[10.617s] [ext: omni.graph.window.generic-1.3.8] startup
[10.619s] [ext: omni.isaac.utils-0.1.11] startup
[10.625s] [ext: omni.isaac.universal_robots-0.2.1] startup
[10.627s] [ext: omni.kit.property.audio-1.0.5] startup
[10.629s] [ext: omni.kit.property.skel-1.0.1] startup
[10.632s] [ext: omni.kit.property.render-1.1.0] startup
[10.634s] [ext: omni.kit.property.camera-1.0.3] startup
[10.635s] [ext: omni.kit.property.geometry-1.2.0] startup
[10.638s] [ext: omni.kit.property.light-1.0.5] startup
[10.641s] [ext: omni.kit.property.transform-1.0.2] startup
[10.645s] [ext: omni.isaac.occupancy_map-0.2

In [ ]:
world._physics_context.is_gpu_dynamics_enabled()

In [ ]:
world.step(render=True)

In [ ]:
world.render()

In [24]:
world.reset()
env.reset_idx([_ for _ in range(8)])

In [76]:
env.reward_buf[[_ for _ in range(8)]] = 0

In [77]:
# torch.save(trainer.policy.state_dict(), "/home/yizhou/Research/Data/718.pth")

In [79]:
# test
for i in range(100):
    total_step += 1
    
    # step
    current_obs = get_obs(env).clone()
    actions, _, _, _  = trainer.policy.actor(current_obs.to(trainer.device), compute_pi=False, compute_log_pi=False)
    # env.robots.set_joint_efforts(efforts = actions.cpu().data * env.motor_efforts)
    reward, done = get_reward_done(env, verbose=False)
    env.reward_buf += reward
    
    world.step(render=True)

In [ ]:
print(total_step, "reward", torch.mean(reward).tolist(), env.reward_buf.tolist())

In [80]:
world.reset()

In [ ]:
# trainer.policy.actor(current_obs.cuda())

# Debug

In [ ]:
world.reset()

In [ ]:
for debug in range(30):
    action_shape = env.action_shape
    
    # if debug % 10 == 0:
    actions =  2 * torch.rand(action_shape) - 1

    # env.robots.set_joint_efforts(efforts = actions *  env.motor_efforts) #.repeat(8, 1)
    # env.robots.set_joint_velocity_targets(actions * 1)

    world.step(render=True)

In [ ]:
env.reset_idx([1])
# env.reset()
# world.step(render=True)

In [ ]:
world.step(render=True)

In [ ]:
get_obs(env)[1]

In [ ]:

torso_position, torso_rotation  = env.robots.get_world_poses()
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])

index = torch.LongTensor([1, 2, 3, 0])
torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW

up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]]
forward_vec = quat_rotate(torso_rotation, torch.tensor([1.0, 0.0, 0.0]).repeat((env.num_envs, 1)))[...,[2]]

# root velocity
root_velocity = env.robots.get_velocities()
velocity = root_velocity[:, 0:3]
ang_velocity = env.angular_velocity_scale * root_velocity[:, 3:] # scaled

# joint position and velocity
dof_pos = (2 * env.robots.get_joint_positions() - env.joint_upper_limit - env.joint_lower_limit) / (env.joint_upper_limit - env.joint_lower_limit) # scale to [-1, 1]
dof_vel = env.robots.get_joint_velocities() * env.dof_vel_scale # scaled

# get obs
obs = torch.cat([up_vec, forward_vec, torso_local_position, torso_rotation, velocity, ang_velocity, dof_pos, dof_vel], dim = 1)


In [ ]:
torso_local_position[1]

In [ ]:
torso_rotation[1]

In [ ]:
velocity[1]

In [ ]:
ang_velocity[1]

In [ ]:
env.robots.get_joint_positions()[1]

In [ ]:
dof_vel[1]

In [ ]:
env.robots._physics_view.get_root_velocities()[1]

In [ ]:
# env.robots._default_state

In [ ]:
dof_pos[1]

In [ ]:
torso_local_position

In [ ]:
# root position
torso_position, torso_rotation  = env.robots.get_world_poses()
index = torch.LongTensor([1, 2, 3, 0])
torso_rotation = torch.index_select(torso_rotation, 1, index) # WXYZ -> XYZW

# get reward 
torso_local_position = torso_position - torch.tensor([[2.0 * (j % 4), 0.0 , 2.0 * (j // 4)] for j in range(env.num_envs)])
target_local_position = torch.tensor([0.0, 0.9, -0.4]).repeat(env.num_envs, 1)

root_dist = torch.sum((torso_local_position - target_local_position)**2, dim = 1)
up_vec = quat_rotate(torso_rotation, torch.tensor([0.0, 0.0, 1.0]).repeat((env.num_envs, 1)))[...,[1]].view(-1)

joint_positions = env.robots.get_joint_positions() 
joint_dist = torch.sum((joint_positions - sit_position_target)**2 / (env.joint_upper_limit - env.joint_lower_limit)**2, \
                       dim = 1)

root_velocity = torch.sum(env.robots.get_velocities()[...,:3]**2, dim = 1)

# reward = torch.exp(-joint_dist) * up_vec  * torch.exp(-root_dist) * torch.exp(-root_velocity) 
reward = up_vec  * torch.exp(-root_dist * 5) * torch.exp(-joint_dist)


In [ ]:
get_reward_done(env, True)

In [ ]:
joint_positions- sit_position_target

In [ ]:
sit_position_target

In [ ]:
env.robots.get_joint_positions()[0]

In [ ]:
sit_position_target[0]