In [1]:
from rl.trainer import Trainer

In [2]:
trainer = Trainer(10, 2)

In [3]:
import getpass

user = getpass.getuser()

In [4]:
from omni.isaac.kit import SimulationApp

simulation_app = SimulationApp({"headless": True, "open_usd": f"omniverse://localhost/Users/{user}/test_jetbot.usd", 
                                "livesync_usd": f"omniverse://localhost/Users/{user}/test_jetbot.usd"})


Starting kit application with the fillowing args:  ['/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps/omni.isaac.sim.python.kit', '--/app/tokens/exe-path=/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/exts', '--ext-folder', '/home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/apps', '--portable', '--no-window']
Passing the following args to the base kit application:  ['-f', '/home/yizhou/.local/share/jupyter/runtime/kernel-0309b157-980a-452d-9123-27b4a4c6d351.json

OmniAssetFileFormat


[1.949s] [ext: omni.mdl-0.1.0] startup
[1.986s] [ext: omni.kit.menu.create-1.0.2] startup
[1.988s] [ext: omni.kit.window.file_exporter-1.0.4] startup
[1.990s] [ext: omni.kit.window.drop_support-1.0.0] startup
[1.991s] [ext: omni.kit.material.library-1.3.10] startup
[1.997s] [ext: omni.kit.window.property-1.6.3] startup
[1.999s] [ext: omni.kit.context_menu-1.3.9] startup
[2.005s] [ext: omni.kit.window.file_importer-1.0.4] startup
[2.007s] [ext: omni.kit.stage_templates-1.1.2] startup
[2.010s] [ext: omni.kit.widget.stage-2.6.15] startup
[2.018s] [ext: omni.kit.window.file-1.3.16] startup
[2.020s] [ext: omni.debugdraw-0.1.0] startup
[2.029s] [ext: omni.kit.window.content_browser-2.4.28] startup
[2.039s] [ext: omni.kit.widget.prompt-1.0.1] startup
[2.040s] [ext: omni.kit.property.usd-3.14.8] startup
[2.074s] [ext: omni.hydra.engine.stats-1.0.0] startup
[2.081s] [ext: omni.kit.widget.settings-1.0.0] startup
[2.082s] [ext: omni.graph.tools-1.3.5] startup
[2.103s] [ext: omni.graph.core-2.27.0

2022-07-15 22:44:28 [2,269ms] [Error] [rtx.neuraylib.plugin] [DYNLIB:IO]   0.1   DYNLIB io   error: /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so: cannot open shared object file: No such file or directory
2022-07-15 22:44:28 [2,270ms] [Error] [rtx.neuraylib.plugin] [INDEX:MAIN]   0.1   INDEX  main error: Failed to load /home/yizhou/.local/share/ov/pkg/isaac_sim-2022.1.0/kit/python/bin/libs/iray/libnvindex.so


Warp initialized:
   Version: 0.2.1
   Using CUDA device: NVIDIA GeForce RTX 3090
   Using CPU compiler: /usr/bin/g++
[3.099s] [ext: omni.kit.window.preferences-1.2.1] startup
[3.134s] [ext: omni.kit.ui_test-1.2.0] startup
[3.136s] [ext: omni.graph.ui-1.6.1] startup
[3.211s] [ext: omni.kvdb-0.0.0] startup
[3.214s] [ext: omni.kit.widget.searchfield-1.0.6] startup
[3.216s] [ext: omni.convexdecomposition-1.4.12] startup
[3.219s] [ext: omni.graph.action-1.17.0] startup
[3.233s] [ext: omni.localcache-0.0.0] startup
[3.236s] [ext: omni.usdphysics-1.4.12] startup
[3.239s] [ext: omni.graph.scriptnode-0.5.0] startup
[3.241s] [ext: omni.physx-1.4.12-5.1] startup
[3.267s] [ext: omni.kit.usd_undo-0.1.0] startup
[3.269s] [ext: omni.graph.nodes-1.25.0] startup
[3.288s] [ext: omni.physx.commands-1.4.12-5.1] startup
[3.294s] [ext: omni.syntheticdata-0.2.1] startup
[3.335s] [ext: omni.physx.ui-1.4.12-5.1] startup
[3.421s] [ext: omni.warp-0.2.1] startup
[5.704s] [ext: omni.kit.renderer.capture-0.0.0] st

In [5]:
import omni
from omni.isaac.core import World
from pxr import Gf, Sdf, UsdGeom, UsdShade

import torch
import numpy as np

In [6]:
world = World(physics_dt= 1.0 / 30, backend = "torch")

In [7]:
from omni.isaac.core.utils.stage import set_stage_up_axis

set_stage_up_axis("y")
world.get_physics_context().set_gravity(-9.81)

In [8]:
from omni.isaac.core.utils.stage import get_current_stage
UsdGeom.GetStageUpAxis(get_current_stage())

'Y'

In [9]:
world.get_physics_context()._physics_scene.GetGravityDirectionAttr().Get()

Gf.Vec3f(0.0, -1.0, 0.0)

In [10]:
# get prims
len(list(world.scene.stage.TraverseAll()))

729

In [11]:
world.render()

In [12]:
from rl.robot_env import RobotEnv

env = RobotEnv("/World/envs/*/jetbot", [10.0, 10.0])

In [13]:
world.reset()

In [14]:
env.start()
world.scene.add(env.robots)

simlation context torch None
num_envs 4
default joint state tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]) tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]) tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [15]:
total_step = 0

In [16]:
action_shape = env.robots._default_joints_state.positions.shape

In [17]:
# step
def step(warm_up_steps = 1000):
    env.progress_buf += 1
    if total_step < warm_up_steps:
        actions = 10 * (2 * torch.rand(action_shape) - 1)
    else:
        actions = 10 * trainer.sample_action(current_obs.to(trainer.device))
        
    env.robots.set_joint_velocities(actions)
    
    return actions

In [18]:
# observation
def get_obs():
    torso_position, torso_rotation  = env.robots.get_world_poses()

    dof_pos = env.robots.get_joint_positions()
    dof_vel = env.robots.get_joint_velocities()

    obs = torch.cat([torso_position[...,[1,2]], torso_rotation, dof_pos, 0.1 * dof_vel], dim = 1)

    return obs

In [19]:
def get_reward_done():
    torso_position, _  = env.robots.get_world_poses()
    reward = 10 * torso_position[...,2].clone()
    
    done = torch.where(torso_position[...,2] < -0.5, 1.0, 0.0)
    done = torch.where(env.progress_buf > 1000, torch.ones(done.shape[0]), done)
    
    return reward, done

In [20]:
current_obs = get_obs().data.clone()
reward, done = get_reward_done()

In [21]:
current_obs, reward, done

(tensor([[-1.6958e-02, -4.1089e-03,  7.0911e-01, -6.9760e-01,  7.3104e-02,
           7.1919e-02,  3.3897e-03,  2.7943e-04, -8.0068e-05, -1.3697e-04],
         [-1.6958e-02, -6.6637e-02, -2.0434e-01,  2.0102e-01,  6.8295e-01,
           6.7187e-01,  2.4705e-04,  1.3495e-03,  1.9817e-05,  2.0423e-04],
         [-1.6958e-02,  5.5819e-02,  6.5686e-01, -6.4620e-01,  2.7698e-01,
           2.7249e-01,  5.9838e-04,  6.0042e-04, -4.0208e-03,  2.1139e-03],
         [-1.6958e-02,  1.3668e-02, -3.8181e-01,  3.7562e-01,  6.0199e-01,
           5.9223e-01,  2.4224e-03, -4.1809e-03,  5.6301e-05, -3.3861e-06]]),
 tensor([-0.0411, -0.6664,  0.5582,  0.1367]),
 tensor([0., 0., 0., 0.]))

In [22]:
# need to reset
def reset(done):
    if torch.sum(done) >= 1:
        env_ids = []
        for i in range(len(done)):
            if done[i] > 0:
                env_ids.append(i)

        env.reset_idx(env_ids)

In [23]:
world.step(render=True)

In [26]:
for i in range(100000):
    total_step += 1
    
    # step
    current_obs = get_obs().clone()
    actions = step()
    # actions = 10 * torch.ones(4, 2)
    # env.robots.set_joint_velocities(10 * torch.ones(4, 2))
    world.step(render=False)
    
    # get obs
    new_obs = get_obs().clone()
    
    # get reward done
    reward, done = get_reward_done()
    
    # reset
    reset(done)
    
    # buffer
    trainer.buf.add_batch(current_obs, 0.1 * actions, new_obs, reward, done)
    # print(total_step, "current_obs, actions, new_obs, reward, done \n\n", current_obs, actions, new_obs, reward, done)
    

    # debug
    if total_step % 1000 == 99:
        print(total_step, "reward", torch.mean(reward).tolist())
        world.render()
    
    # train
    if total_step > 1000:
        trainer.train_debug(batch_size = 32)
    
    

11099 reward 1.8965692520141602
12099 reward 1.226741075515747
13099 reward 11.225682258605957
14099 reward 3.710864543914795
15099 reward 25.747421264648438
16099 reward 13.528891563415527
17099 reward 3.0023953914642334
18099 reward 12.764226913452148
19099 reward 23.02794075012207
20099 reward 16.30008888244629
21099 reward 11.695813179016113
22099 reward 20.615360260009766
23099 reward 3.6890244483947754
24099 reward 5.016439437866211
25099 reward 21.05942153930664
26099 reward 19.894643783569336
27099 reward 19.79549789428711
28099 reward 26.892061233520508
29099 reward 4.886970043182373
30099 reward 10.601360321044922
31099 reward 7.6523308753967285
32099 reward 3.9452171325683594
33099 reward 4.744142532348633
34099 reward 13.566095352172852
35099 reward 10.389758110046387
36099 reward 23.1983642578125
37099 reward 3.6956143379211426
38099 reward 12.152158737182617
39099 reward 12.224940299987793
40099 reward 10.150224685668945
41099 reward 15.241021156311035
42099 reward 8.9903

In [22]:
world.reset()

In [26]:
world.render()